import Foundation

/// A comprehensive report generated by the AudioIntelligence analyzer.
public struct AudioReport: Sendable {
    /// Human-friendly summary of the analysis.
    public let summary: String
    
    /// Analyzed rhythm details, such as BPM.
    public let rhythm: RhythmResult?
    
    /// Analyzed forensic details, if requested.
    public let forensic: ForensicResult?
    
    /// Represents rhythm-related analysis results.
    public struct RhythmResult: Sendable {
        public let bpm: Double
        public let confidence: Double
    }
    
    /// Represents forensic-related analysis results.
    public struct ForensicResult: Sendable {
        public let encoderName: String
        public let isAuthentic: Bool
    }
}
