import Foundation
@_exported import AudioIntelligenceCore

/// A comprehensive "Infinity" report generated by the AudioIntelligence platform.
public struct AudioReport: Sendable {
    /// Human-friendly summary of the analysis.
    public let summary: String
    
    /// The deep "Infinity" analysis model (v28.0)
    public let rawAnalysis: MusicDNAAnalysis
    
    /// The final report in Markdown format.
    public let reportText: String
    
    /// Path to the detailed .md file in 'AI Works'.
    public let reportPath: String
}
