import Foundation
import AudioIntelligenceCore

/// A comprehensive report generated by the AudioIntelligence analyzer.
public struct AudioReport: Sendable {
    /// Human-friendly summary of the analysis.
    public let summary: String
    
    /// Professional analysis result (Internal legacy mapping for v25.0)
    public let rawAnalysis: MusicDNAAnalysis
    
    /// The final report in Markdown format.
    public let reportText: String
    
    /// Path to the detailed Markdown file.
    public let reportPath: String
}
